language: python
python:
- '3.7'
install:
- pip3 install PyGithub
script:
- python3 travis_scripts/check_tag.py || travis_terminate 1
- docker build -t function . || travis_terminate 1
deploy:
  - provider: script
    skip_cleanup: true
    script: python3 travis_scripts/push_tag.py
    on:
      branch: main
